name: Build, Provision, and Deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: devops-core-04a-RG

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure with Bicep
        id: deploy_infrastructure
        run: |
          deploymentOutput=$(az deployment group create --resource-group $RESOURCE_GROUP --template-file ./infra/template.bicep --parameters ./infra/parameters.json --output json)
          echo "Deployment Output: $deploymentOutput"

          echo "$deploymentOutput" > deployment_output.txt
          echo "DEPLOYMENT_OUTPUT_FILE=deployment_output.txt" >> $GITHUB_ENV

      - name: Extract Web App Names
        id: extract
        run: |
          deploymentOutputFile=${{ env.DEPLOYMENT_OUTPUT_FILE }}
          cat $deploymentOutputFile
          cat deployment_output.txt

          # Use jq to extract the Web App names
          webAppNameWestUS=$(jq -r '.properties.outputResources[] | select(.id | endswith("webapp-westus")).id | split("/") | .[-1]' "$deploymentOutputFile")
          webAppNameEastUS=$(jq -r '.properties.outputResources[] | select(.id | endswith("webapp-eastus")).id | split("/") | .[-1]' "$deploymentOutputFile")

          echo "Web App Name West US: $webAppNameWestUS"
          echo "Web App Name East US: $webAppNameEastUS"

          echo "WEBAPPNAMEWESTUS=$webAppNameWestUS" >> $GITHUB_ENV
          echo "WEBAPPNAMEEASTUS=$webAppNameEastUS" >> $GITHUB_ENV

        shell: bash
        env:
          DEPLOYMENT_OUTPUT_FILE: ${{ env.DEPLOYMENT_OUTPUT_FILE }}

      - name: Retrieve Publish Profile for West US
        id: get-publish-profile-westus
        run: |
          az webapp deployment list-publishing-profiles --name ${{ env.WEBAPPNAMEWESTUS }} --resource-group $RESOURCE_GROUP --query '[?publishMethod==`MSDeploy`].{name:name, url:publishUrl, profile:publishProfile}' --output json > publishProfileWestUS.json
          echo "publishProfileWestUS: $(cat publishProfileWestUS.json)"
          echo "PUBLISHPROFILEWESTUS=$publishProfileWestUS" >> $GITHUB_ENV

        shell: bash
        env:
          WEBAPPNAMEWESTUS: ${{ env.WEBAPPNAMEWESTUS }}

      - name: Retrieve Publish Profile for East US
        id: get-publish-profile-eastus
        run: |
          az webapp deployment list-publishing-profiles --name ${{ env.WEBAPPNAMEEASTUS }} --resource-group $RESOURCE_GROUP --query '[?publishMethod==`MSDeploy`].{name:name, url:publishUrl, profile:publishProfile}' --output json > publishProfileEastUS.json
          echo "publishProfileEastUS: $(cat publishProfileEastUS.json)"
          echo "PUBLISHPROFILEEASTUS=$publishProfileEastUS" >> $GITHUB_ENV

        shell: bash
        env:
          WEBAPPNAMEEASTUS: ${{ env.WEBAPPNAMEEASTUS }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App (West US)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPPNAMEEASTUS }}
          slot-name: 'Production'
          package: .
          publish-profile: ${{ env.PUBLISHPROFILEWESTUS }}

      - name: Deploy to Azure Web App (East US)
        id: deploy-to-webapp-east
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPPNAMEEASTUS }}
          slot-name: 'Production'
          package: .
          publish-profile: ${{ env.PUBLISHPROFILEEASTUS }}